# Generated by Django 4.0.3 on 2022-03-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mytodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Task',
            new_name='task',
        ),
    ]
