# Generated by Django 4.0.3 on 2022-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mytodo', '0003_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
